### ISSUE TITLE
Raft选举问题

### ISSUE THREAD

**Issue by HsyAiden** [leakey0626/Raft-KV#1]
```java
// 没有投票出去或者投票的是当前候选node
if ((StringUtil.isNullOrEmpty(votedFor) || votedFor.equals(param.getCandidateAddr()))){
 //省略
}
```
上述代码是你的投票判断，也就是在一次选举的过程中，一个node只能投票给一个候选者。

但是在查阅资料中得知，在一次选举中，一个node应该可以给多个候选者投票，具体如下：
"在一次选举中，每一个服务器节点最多会对一个任期编号投出一张选票，并且按照“先来先服务”的原则进行投票"

**Comment by leakey0626** [comment]
确实是有问题，应该要在某个地方把 votedFor 设为空

**Comment by leakey0626** [comment]
可以看看最新的commit

**Comment by leakey0626** [comment]
fixed
